spring.application.name=user-service

# Cổng chạy của User Service 
server.port=8081

# Cấu hình Kafka (Nếu nhóm dùng Kafka) 
# Thay 192.168.?.? bằng IP của máy Người 5 đang chạy Broker

# spring.kafka.bootstrap-servers=192.168.?.?:9092
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
